"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os

from pathlib import Path

from split_settings.tools import include
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()
include(
    os.path.join(".", "components", "security.py"),
    os.path.join(".", "components", "app_definition.py"),
    os.path.join(".", "components", "database.py"),
    os.path.join(".", "components", "auth.py"),
    os.path.join(".", "components", "internationalization.py"),
)

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
